### ISSUE TITLE
GOG Galaxy 2.0 now automatically updates "Community integrations - popular" integrations

### ISSUE THREAD

**Issue by JanPokorny** [borger/scoop-galaxy-integrations#5]
GOG Galaxy 2.0 now seems to automatically download new versions of the "Community integrations - popular" integrations to the `C:\Users\<username>\AppData\Local\GOG.com\Galaxy\plugins\installed` folder. In the process, it automatically removes the symlink created by this bucket, breaking the `scoop update`. 

As such, I propose removing the "Community integrations - popular" integrations from this bucket -- i.e. `galaxy-epic`, `galaxy-origin`, `galaxy-psn`, `galaxy-steam` and `galaxy-uplay`. They are not needed here as GOG Galaxy itself now manages their updates.

**Comment by borger** [comment]
@JanPokorny , can you provide more details on how you got to this conclusion? Most of the integrations installed on my PC are from FriendsOfGalaxy however, I haven't had an issue with updates, or the symlinks. An auto-update feature does make sense, however, the install procedure is still tricky for a few options. Thanks!

**Comment by JanPokorny** [comment]
@borger Note that I originally mis-stated this as all FriendsOfGalaxy integrations -- only integrations that autodownload seem to be the ones from the "Community integrations - popular" section, i.e. the five stated in the top post.

I noticed that `scoop update` errored out on two integrations (Steam, Origin) that had new versions. The error was that it was unable to find the path `C:\Users\<username>\AppData\Local\GOG.com\Galaxy\plugins\installed\steam` (or `origin`, respectively). I investigated and it turned out that the symlinks were removed, and new `steam_*` and `origin_*` folders were created in their place, with the date of creation the last time I opened Galaxy. Other symlinks were still there. Thus Galaxy must have autoupdated the integrations itself. I was able to confirm that if I delete the integration folders, they are autodownloaded on next start of Galaxy.

It is completely possible that you never encountered this issue, if you run `scoop update *` every time before launching Galaxy. (Or perhaps Galaxy has some delay in recognizing there's a new version available?)

**Comment by borger** [comment]
That's interesting! One question for you, did you install any of the "Community integrations - popular" (at least once) via Galaxy itself? 

Something weird happened to me in the early days of this bucket, is that I had a few integrations installed from the Galaxy app that were outdated, and when I installed them again via scoop (deleting the existing folders first) I got the entries duplicated in Galaxy's Settings page (only there), like the folder was still there. However a reboot on Galaxy solved the issue. I did think scoop was going to be a problem. Now, you may be right that I run scoop update at least once a day, and when I open Galaxy they are already updated. 

I'll keep this issue open, as I need more reports on this. To me, if this happens the way you've reported, it's actually okay, because it means you can install from scoop, and Galaxy sees it and start to manage it itself, from that point there's no link with the scoop installed integration anymore, the only thing which will not make sense in this scenario are the scoop updates which generally are manual anyway. I'll run some tests to see what can be done here, as well as attempt to replicate your report. I'll post here as soon as I have news. 

If you have any suggestions, feel free to add them here.

**Comment by JanPokorny** [comment]
@borger 

> did you install any of the "Community integrations - popular" (at least once) via Galaxy itself?

Yes, I did.

Steps to reproduce:
- stop Galaxy
- remove all versions of `steam` from `C:\Users\<username>\AppData\Local\GOG.com\Galaxy\plugins\installed\` (including `scoop uninstall`)
- install an older version of Steam integration (0.32) and agree to create the symlink: `scoop install https://raw.githubusercontent.com/borger/scoop-galaxy-integrations/eaa6d9da5ac33661f670a0c7c83468958707fba2/galaxy-steam.json`
- observe that the symlink is correctly created
- open Galaxy
- wait several minutes
- observe that new folder has been downloaded, containing the newest version of Steam integration (0.33):
   ![obrazek](https://user-images.githubusercontent.com/4580066/67918445-9c769d80-fb9c-11e9-8ddb-a904b4aaa808.png)
   (I was unable to reproduce Galaxy removing the `steam` symlink, although it definitely happened last time -- I believe this is caused by some open process blocking the symlink.)

From this I conclude that having the five integrations from "Community integrations - popular" in this bucket is redundant and potentially confusing (as `scoop update *` might error out when Galaxy removes the symlink).

**Comment by borger** [comment]
Thank you @JanPokorny . I'm testing your steps now, I'm about 30 mins in (confirmed it's on v0.32), no changes as of now, I'll leave Galaxy open (and don't `scoop update * `) until it does. Yours took about 6 mins to do its thing. Let's see...

1) Say it does happen, what then!? Changes nothing, if you update via `scoop update *` it **will not** error out, because it will update exclusively `%homepath%\scoop\apps\<manifest-name>` regardless of having the symlink or not on `%localappdata%\GOG.com\Galaxy\plugins\installed\<manifest-name>` which is what Galaxy actually uses. Worst that can happen is you end up with two folders for the same integration, with Galaxy preferring its own copy, which is okay. I would prefer it this way: Galaxy auto-updating its integrations. I've built this bucket because it doesn't (for my integrations anyway).

2) Now, say it doesn't happen. You can continue to use the scoop to update your integrations or use [Slashbunny's](https://github.com/Slashbunny/gog-galaxy-plugin-downloader) alternative. My theory is that it may happen because you've installed it via Galaxy itself, it would make sense since it thinks it manages the integration. 

It's really up to what you prefer, you can uninstall the integrations that are being duplicated by Galaxy when it downloads the newer version with `scoop uninstall <manifest-name>`. And all folders (and symlinks if present) created by this bucket will be removed. 

As for redundancy, I agree! This bucket is redundant, the post-install process actually checks for duplicates and warns you if it finds any. I believe once Galaxy 2.0 is released, this bucket will no longer be needed, however for the early adopters/beta testers out there, myself included, can choose to use this bucket as their controller for the integrations installed and keep them updated.

**Comment by JanPokorny** [comment]
@borger It did not occur to me that this might not be universal behavior. Does it not update even after restarting Galaxy again? Perhaps it's some kind of A/B test I'm in and you aren't.

Also, I found a way to replicate the original error. This happens when Galaxy removes the symlink.

![obrazek](https://user-images.githubusercontent.com/4580066/67946579-edf54b80-fbe1-11e9-8e78-3f4ffd88e151.png)

Looks like the rest of (un)installation happens normally, though.

I agree that if Galaxy does not universally update integrations, then you should keep those five in the bucket. However I would suggest fixing the case when the symlink does not exist (to remove the ugly error) and perhaps better handle the case when multiple integrations folders already exist (which may happen after every update) -- either tell user it's ok, or move them all to `$persist_dir\backup` like you do with the one blocking the symlink name.

**Comment by borger** [comment]
Hello @JanPokorny , I was finally able to replicate. So, I had Galaxy opened since yesterday, no issues, I've restarted Galaxy 4 times, and left open for about 10 minutes each time, on the 4th time, it did download its own version of the steam integration, but it did not destroy the symlink in this test, that's not to say it can't happen, I left it open to see that what it does. 

I've also tried to uninstall and got the same error you posted above, I apologize because I misunderstood when you said it will "error out" to me you were referring to the actual scoop process, as you said, although it didn't fail to complete it did print the horrendous error.

I like your idea to prepare the script to verify it, a try/catch would do, I'll work on it asap and push here. Thank you for your help with this!

**Comment by JanPokorny** [comment]
@borger Looks like Galaxy now can install (and presumably update) all of the following:

![obrazek](https://user-images.githubusercontent.com/4580066/69156315-8137e780-0ae3-11ea-959a-a34447bfc450.png)

Note that, curiously, this is all of the @FriendsOfGalaxy integrations _except_ [Battle.net](https://github.com/FriendsOfGalaxy/galaxy-integration-battlenet/).

**Comment by borger** [comment]
That's interesting @JanPokorny thank you! I wonder how it'll work once it gets out of beta especially for non FriendsOfGalaxy ones.

**Comment by JanPokorny** [comment]
@borger As @FriendsOfGalaxy is basically their proxy account for auditing community-made integrations (you probably know that most are just active forks of some 3rd party repo), I highly doubt that integrations from other GitHub accounts can get on the list. I expect the only way there would be convincing @FriendsOfGalaxy to fork and audit your integration. So this bucket may prove useful even after the end of beta, for lesser-known integrations, like the emulators.

**Comment by borger** [comment]
yes, I meant for those that are likely never getting onboard FOG's review list, emulators is a sample, but for instance at some point we'll have PSN/Now integration, which I believe can be easier via community, however, will be hardly supported by FOG unless SONY themselves do it, similar to the discord integration situation, it works, but it may be not okay with TOS. Let's see, I'm curious about how it'll work.
