### ISSUE TITLE
PS2 and PS3 additions?

### ISSUE THREAD

**Issue by Deide** [borger/scoop-galaxy-integrations#8]
There are integrations for [Playstation 2](https://github.com/AHCoder/galaxy-integration-ps2) and [Playstation 3](https://github.com/mpm11011/galaxy-integration-rpcs3).

Any interest in adding them?

**Comment by borger** [comment]
Hi @Deide,

Sure! On the PlayStation 3 personally, I wouldn't use as its not using its actual platform (on the GOG Galaxy side), its reported as "ColecoVision" because there's no playstation 3 platform [here](https://github.com/gogcom/galaxy-integrations-python-api/blob/master/PLATFORM_IDs.md). It may not be an issue to everyone else, so I think its okay to add both here. Feel free to create a PR for it, or allow me a few days to work on it.

Thanks!

**Comment by borger** [comment]
Hello @Deide ,

Thank you for your PR, I've reviewed and approved!

**Comment by Deide** [comment]
Cool! The PS3 manifest can be added once they finally add the platform; not sure what's taking so long.
